# Generated by Django 2.0.1 on 2018-02-21 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etiquettes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiquettes_nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Extraits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraits_content', models.CharField(max_length=2000)),
                ('extraits_titre', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='R_Extraits_Etiquettes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiquettes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digressions.Etiquettes')),
                ('extraits_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digressions.Extraits')),
            ],
        ),
        migrations.AddField(
            model_name='commentaires',
            name='titre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='digressions.Extraits'),
        ),
    ]
