# Generated by Django 2.0.1 on 2018-01-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquettes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiquettes_nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Extraits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraits_content', models.CharField(max_length=2000)),
                ('extraits_titre', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='R_Extraits_Etiquettes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiquettes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digressions.Etiquettes')),
                ('extraits_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digressions.Extraits')),
            ],
        ),
    ]
