# Generated by Django 2.0.1 on 2018-03-02 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digressions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraits',
            name='extraits_livre',
            field=models.CharField(default='du coté de chez Swann', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentaires',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentaires',
            name='titre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='digressions.Extraits'),
        ),
    ]
