# Generated by Django 2.0.1 on 2018-03-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digressions', '0002_auto_20180302_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraits',
            name='extraits_livre',
        ),
    ]
