# Generated by Django 2.0.1 on 2018-03-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digressions', '0003_remove_extraits_extraits_livre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livre_titre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='extraits',
            name='extraits_livre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='digressions.Livre'),
            preserve_default=False,
        ),
    ]
