# Generated by Django 2.0 on 2018-03-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digressions', '0004_auto_20180303_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraits',
            name='extraits_livre_id',
        ),
        migrations.AddField(
            model_name='extraits',
            name='extraits_livre_id',
            field=models.ForeignKey(default='du coté de chez Swann', on_delete=django.db.models.deletion.CASCADE, to='digressions.Livre'),
            preserve_default=False,
        ),
    ]
