# Generated by Django 2.0 on 2018-03-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digressions', '0005_auto_20180306_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraits',
            old_name='extraits_livre_id',
            new_name='extraits_livre',
        ),
    ]
