# Generated by Django 2.0 on 2018-03-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digressions', '0007_auto_20180306_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraits',
            old_name='extraits_livre_id',
            new_name='extraits_livre',
        ),
    ]
